@echo off
echo 🔄 Riavvio Frontend Server...
cd /d "c:\Users\AlessioAndriulo\Music\UniHomes\frontend"

echo 🛑 Fermando processi Node esistenti...
taskkill /f /im node.exe 2>nul

echo 🧹 Pulizia cache...
if exist node_modules\.vite rmdir /s /q node_modules\.vite

echo 🚀 Riavvio server di sviluppo...
npm run dev
